---
# playbook.yml
- name: 'Validate Image'
  hosts: all
  become: true
  tasks:
    - name: Gather the package facts
      ansible.builtin.package_facts:
        manager: auto

    - name: Check if curl is installed
      ansible.builtin.debug:
        msg: "Package 'curl' is installed!"
      when: "'curl' in ansible_facts.packages"

    - name: Check if unzip is installed
      ansible.builtin.debug:
        msg: "Package 'unzip' is installed!"
      when: "'unzip' in ansible_facts.packages"
